image: ruby:3.1

before_script:
  - gem install bundler
  - bundle install

build:
  stage: build
  script:
    - bundle exec jekyll build -d public  # 注意：GitLab Pages 要輸出到 public
  artifacts:
    paths:
      - public  # GitLab Pages 只接受 public 資料夾
  only:
    - main  # 或 master，視你的預設分支而定

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main  # 或 master

